backend:
  name: github
  repo: kewei/kewei.github.io
  branch: master
  base_url: https://kewei-github-io.netlify.app
  auth_endpoint: /externalauth/github
site_url: https://kewei.github.io
display_url: https://kewei.github.io
media_folder: "static/images" # Where images are stored in repo
public_folder: "/images"      # Where Hugo looks for images
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
